server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    location /task1/ {
        try_files $uri $uri/ /task1/index.html;
    }

    location ~* \.(md|txt|csv|json|gs)$ {
        default_type text/plain;
        add_header Content-Type "text/plain; charset=utf-8";
    }

    location ~* \.zip$ {
        default_type application/zip;
        add_header Content-Disposition "attachment";
    }
}
